# ==============================================================
# = Articoli Web Service con Autenticazione JWT
# ==============================================================

server:
  port: 9100


# ==============================================================
# = Actuator Parameters
# ==============================================================
management:

  endpoints:
    web:
      exposure:
        include: "*"


      
# ==============================================================
# = Actuator Info
# ==============================================================
info:
  assistenza:
    nome: "Pippo"
    mail: "pippo@gmail.cot"
    telefono: "33333338"

  nome:
    nome-app: "prova attuatore"

