server.port=8080

#aggiunge endpoint personalizzati
#/actuator/customstatus
management.endpoints.web.exposure.include=*

#per aggiungere i singoli endpoint
#management.endpoints.web.exposure.include=health,info,metrics,loggers


#abilita automaticamente l'inclusione delle variabili d ambiente (env) nell 
#endpoint /actuator/info
management.info.env.enabled=true

info.app.name=ActuatorDemo
info.app.version=1.0.0

#non nasconde il valore delle properties su actuators
management.endpoint.env.show-values=ALWAYS
