name: SpringSentinel

on:
  push:
  pull_request:

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Run SpringSentinel
        uses: pagano-antonio/springsentinel-action@main
          
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: target/spring-sentinel-reports/report.sarif

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: spring-sentinel-report
          path: target/spring-sentinel-reports/
