name: SpringSentinel

on:
  push:
  pull_request:

permissions:
  contents: read
  actions: read
  security-events: write
  pull-requests: write
  issues: write

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Run SpringSentinel
        uses: pagano-antonio/springsentinel-action@main
          
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: target/spring-sentinel-reports/report.sarif

      - name: Upload SpringSentinel Reports
        uses: actions/upload-artifact@v4
        with:
          name: spring-sentinel-report
          path: target/spring-sentinel-reports/

      - name: Publish PR comment
        if: github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            --body-file target/spring-sentinel-reports/comment.md
